<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Storage;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'email' => 'admin@example.com',
                'password' => Hash::make('admin123'),
                'name' => `git config user.name`,
                'phone' => '0365829471',
                'address' => '13 P. Trịnh Văn Bô, Xuân Phương, Nam Từ Liêm, Hà Nội',
                'avatar' => 'https://i.pinimg.com/1200x/16/4b/99/164b9961daa4c63de56d28398d555f6b.jpg',
                'birthday' => '2005-07-18',
                'gender' => 'other',
                'role' => 'admin',
                'status' => 'active',
            ],
            [
                'email' => 'staff@example.com',
                'password' => Hash::make('staff123'),
                'name' => `git config user.name`,
                'phone' => '0365829471',
                'address' => '13 P. Trịnh Văn Bô, Xuân Phương, Nam Từ Liêm, Hà Nội',
                'avatar' => 'https://jbagy.me/wp-content/uploads/2025/03/hinh-anh-cute-avatar-vo-tri-3.jpg',
                'birthday' => '2005-07-18',
                'gender' => 'other',
                'role' => 'staff',
                'status' => 'active',
            ],
            [
                'email' => 'user@example.com',
                'password' => Hash::make('user123'),
                'name' => `git config user.name`,
                'phone' => '0365829471',
                'address' => '13 P. Trịnh Văn Bô, Xuân Phương, Nam Từ Liêm, Hà Nội',
                'avatar' => 'https://jbagy.me/wp-content/uploads/2025/03/Hinh-anh-avatar-nam-cute-2.jpg',
                'birthday' => '2005-07-18',
                'gender' => 'other',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'thanhlam95@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Trần Thanh Lâm',
                'phone' => '0385129347',
                'address' => '12 Nguyễn Huệ, Phường Bến Nghé, Quận 1, TP. Hồ Chí Minh',
                'avatar' => 'https://www.in.pro.vn/wp-content/uploads/2025/01/avatar-nam-giau-mat.webp',
                'birthday' => '1995-03-12',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'nguyenhoanganh@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Nguyễn Hoàng Anh',
                'phone' => '0912873645',
                'address' => '45 Lê Lợi, Phường Thạch Thang, Quận Hải Châu, TP. Đà Nẵng',
                'avatar' => 'https://dimensions.edu.vn/public/upload/2025/01/avatar-tiktok-dep-4.webp',
                'birthday' => '2001-07-25',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'banned',
            ],
            [
                'email' => 'phamtrang1905@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Phạm Thị Thu Trang',
                'phone' => '0856124739',
                'address' => '78 Trần Phú, Phường Hàng Bạc, Quận Hoàn Kiếm, Hà Nội',
                'avatar' => 'https://dimensions.edu.vn/public/upload/2025/01/avatar-gai-xinh-toc-ngan-4.webp',
                'birthday' => '1998-05-19',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'leminhtuan2002@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Lê Minh Tuấn',
                'phone' => '0709128346',
                'address' => '56 Nguyễn Văn Linh, Phường An Khánh, Quận Ninh Kiều, Cần Thơ',
                'avatar' => 'https://scr.vn/wp-content/uploads/2020/07/H%C3%ACnh-avatar-m%C3%A8o-d%E1%BB%85-th%C6%B0%C6%A1ng.jpg',
                'birthday' => '2002-08-08',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'inactive',
            ],
            [
                'email' => 'dangthao04@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Đặng Thị Bích Thảo',
                'phone' => '0367128495',
                'address' => '23 Võ Nguyên Giáp, Phường Trường Thi, TP. Vinh, Nghệ An',
                'avatar' => 'https://wellavn.com/wp-content/uploads/2024/11/gai-xinh-cute-anh-dai-dien-dep-cho-nu-5.jpg',
                'birthday' => '1997-04-14',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'vanson2000@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Võ Văn Sơn',
                'phone' => '0395847126',
                'address' => '12 Nguyễn Văn Cừ, Phường An Bình, Quận Ninh Kiều, Cần Thơ',
                'avatar' => 'https://anhdephd.vn/wp-content/uploads/2022/06/anh-trai-dep-che-mat-dep-nhat.jpg',
                'birthday' => '2000-11-03',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'ngohuong1996@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Ngô Thị Hương',
                'phone' => '0827645913',
                'address' => '25 Lạch Tray, Phường Lạch Tray, Quận Ngô Quyền, Hải Phòng',
                'avatar' => 'https://ieclanguage.edu.vn/wp-content/uploads/2025/03/anh-avatar-dep-14.jpg',
                'birthday' => '1996-09-21',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'dung29012002@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Trần Văn Dũng',
                'phone' => '0908123745',
                'address' => '34 Nguyễn Trãi, Phường Phạm Ngũ Lão, Quận 1, TP. Hồ Chí Minh',
                'avatar' => 'https://jbagy.me/wp-content/uploads/2025/03/anh-avatar-vo-tri-hai-cute-2.jpg',
                'birthday' => '2002-01-29',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'banned',
            ],
            [
                'email' => 'nguyenthithu99@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Nguyễn Thị Thu',
                'phone' => '0378459126',
                'address' => '12 Hùng Vương, Phường An Lạc, Quận Bình Tân, TP. Hồ Chí Minh',
                'avatar' => 'https://dongvat.edu.vn/upload/2024/12/avatar-cute-meo-02.webp',
                'birthday' => '1999-06-11',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'hoangphucproplayer@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Hoàng Quốc Phúc',
                'phone' => '0789126345',
                'address' => '78 Nguyễn Du, Phường Bến Thành, Quận 1, TP. Hồ Chí Minh',
                'avatar' => 'https://phunugioi.com/wp-content/uploads/2020/10/avatar-doremon-lam-thuy-thu.jpg',
                'birthday' => '1993-02-15',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'phammailinh@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Phạm Mai Linh',
                'phone' => '0895412637',
                'address' => '45 Nguyễn Văn Thoại, Phường Mỹ An, Quận Ngũ Hành Sơn, TP. Đà Nẵng',
                'avatar' => 'https://bom.edu.vn/public/upload/2024/12/avatar-anh-gai-14.webp',
                'birthday' => '1995-12-09',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'inactive',
            ],
            [
                'email' => 'dangbao271097@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Đặng Minh Bảo',
                'phone' => '0928457136',
                'address' => '67 Trần Hưng Đạo, Phường Cửa Nam, Quận Hoàn Kiếm, Hà Nội',
                'avatar' => 'https://photo.znews.vn/w660/Uploaded/ohunua2/2017_04_10/duong3.jpg',
                'birthday' => '1997-10-27',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'tranhonganh2000@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Trần Thị Hồng Anh',
                'phone' => '0354918267',
                'address' => '89 Nguyễn Văn Linh, Phường Nam Dương, Quận Hải Châu, TP. Đà Nẵng',
                'avatar' => 'https://maunhi.com/wp-content/uploads/2025/04/avatar-dep-5.jpg',
                'birthday' => '2000-04-03',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'nguyenlong0505@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Nguyễn Văn Long',
                'phone' => '0974812653',
                'address' => '23 Hòa Bình, Phường 3, TP. Cao Lãnh, Đồng Tháp',
                'avatar' => 'https://thuthuatnhanh.com/wp-content/uploads/2020/09/hinh-avatar-dep-cho-nam.jpg',
                'birthday' => '2004-05-05',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'active',
            ],
            [
                'email' => 'dothihanh93@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Đỗ Thị Hạnh',
                'phone' => '0395841267',
                'address' => '56 Bạch Đằng, Phường Hải Châu 1, Quận Hải Châu, TP. Đà Nẵng',
                'avatar' => 'https://weart.vn/wp-content/uploads/2025/06/hinh-anh-co-gai-deo-kinh-can-dang-yeu-voi-nu-cuoi-nhe-nhang.jpg',
                'birthday' => '1993-11-12',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'banned',
            ],
            [
                'email' => 'minhtien1894@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Nguyễn Minh Tiến',
                'phone' => '0812459736',
                'address' => '12 Phan Đình Phùng, Phường 2, TP. Đà Lạt, Lâm Đồng',
                'avatar' => 'https://i.pinimg.com/736x/54/d6/fb/54d6fbb62d49d8f48fc485c22ff81f3d.jpg',
                'birthday' => '1994-09-18',
                'gender' => 'man',
                'role' => 'user',
                'status' => 'inactive',
            ],
            [
                'email' => 'phamthiyen30@gmail.com',
                'password' => Hash::make('12345678'),
                'name' => 'Phạm Thị Yến',
                'phone' => '0347859126',
                'address' => '45 Trần Quang Khải, Phường Tân Định, Quận 1, TP. Hồ Chí Minh',
                'avatar' => 'https://cdn2.fptshop.com.vn/unsafe/avatar_nu_02_7aaee331e8.jpg',
                'birthday' => '1999-07-30',
                'gender' => 'woman',
                'role' => 'user',
                'status' => 'active',
            ]
        ];

        foreach ($data as $user) {
            $dataAvatar = file_get_contents($user['avatar'], false, stream_context_create([
                'http' => [
                    'method' => 'GET',
                    'ignore_errors' => true
                ],
            ]));

            $avatar = "users/" . uniqid('avatar_') . basename($user['avatar']);
            Storage::drive('public')->put($avatar, $dataAvatar);

            User::create(array_merge($user, ['avatar' => $avatar]));
        }
    }
}
